/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
#ifndef _DT_BINDINGS_MEMORY_MT6797_LARB_PORT_H_
#define _DT_BINDINGS_MEMORY_MT6797_LARB_PORT_H_

#include <dt-bindings/memory/mtk-memory-port.h>

#define M4U_LARB0_ID			0
#define M4U_LARB1_ID			1
#define M4U_LARB2_ID			2
#define M4U_LARB3_ID			3
#define M4U_LARB4_ID			4
#define M4U_LARB5_ID			5
#define M4U_LARB6_ID			6

/* larb0: display and MDP */
#define M4U_PORT_DISP_OVL0		MTK_M4U_ID(M4U_LARB0_ID, 0)
#define M4U_PORT_DISP_2L_OVL0_LARB0	MTK_M4U_ID(M4U_LARB0_ID, 1)
#define M4U_PORT_DISP_RDMA0		MTK_M4U_ID(M4U_LARB0_ID, 2)
#define M4U_PORT_DISP_WDMA0		MTK_M4U_ID(M4U_LARB0_ID, 3)
#define M4U_PORT_MDP_RDMA0		MTK_M4U_ID(M4U_LARB0_ID, 4)
#define M4U_PORT_MDP_WDMA0		MTK_M4U_ID(M4U_LARB0_ID, 5)
#define M4U_PORT_MDP_WROT0		MTK_M4U_ID(M4U_LARB0_ID, 6)
#define M4U_PORT_DISP_FAKE_LARB0	MTK_M4U_ID(M4U_LARB0_ID, 7)

/* larb1: video decoder */
#define M4U_PORT_VDEC_MC		MTK_M4U_ID(M4U_LARB1_ID, 0)
#define M4U_PORT_VDEC_PP		MTK_M4U_ID(M4U_LARB1_ID, 1)
#define M4U_PORT_VDEC_UFO		MTK_M4U_ID(M4U_LARB1_ID, 2)
#define M4U_PORT_VDEC_VLD		MTK_M4U_ID(M4U_LARB1_ID, 3)
#define M4U_PORT_VDEC_VLD2		MTK_M4U_ID(M4U_LARB1_ID, 4)
#define M4U_PORT_VDEC_AVC_MV		MTK_M4U_ID(M4U_LARB1_ID, 5)
#define M4U_PORT_VDEC_PRED_RD		MTK_M4U_ID(M4U_LARB1_ID, 6)
#define M4U_PORT_VDEC_PRED_WR		MTK_M4U_ID(M4U_LARB1_ID, 7)
#define M4U_PORT_VDEC_PPWRAP		MTK_M4U_ID(M4U_LARB1_ID, 8)
#define M4U_PORT_VDEC_TILE		MTK_M4U_ID(M4U_LARB1_ID, 9)

/* larb2: camera */
#define M4U_PORT_CAM_IMGO		MTK_M4U_ID(M4U_LARB2_ID, 0)
#define M4U_PORT_CAM_RRZO		MTK_M4U_ID(M4U_LARB2_ID, 1)
#define M4U_PORT_CAM_AAO		MTK_M4U_ID(M4U_LARB2_ID, 2)
#define M4U_PORT_CAM_AFO		MTK_M4U_ID(M4U_LARB2_ID, 3)
#define M4U_PORT_CAM_LSCI_0		MTK_M4U_ID(M4U_LARB2_ID, 4)
#define M4U_PORT_CAM_LSCI_1		MTK_M4U_ID(M4U_LARB2_ID, 5)
#define M4U_PORT_CAM_SV0		MTK_M4U_ID(M4U_LARB2_ID, 6)
#define M4U_PORT_CAM_SV1		MTK_M4U_ID(M4U_LARB2_ID, 7)
#define M4U_PORT_CAM_SV2		MTK_M4U_ID(M4U_LARB2_ID, 8)
#define M4U_PORT_CAM_LCSO		MTK_M4U_ID(M4U_LARB2_ID, 9)
#define M4U_PORT_CAM_UFEO		MTK_M4U_ID(M4U_LARB2_ID, 10)
#define M4U_PORT_CAM_BPCI		MTK_M4U_ID(M4U_LARB2_ID, 11)
#define M4U_PORT_CAM_PDO		MTK_M4U_ID(M4U_LARB2_ID, 12)
#define M4U_PORT_CAM_RAWI		MTK_M4U_ID(M4U_LARB2_ID, 13)

/* larb3: video and JPEG codecs */
#define M4U_PORT_VENC_RCPU		MTK_M4U_ID(M4U_LARB3_ID, 0)
#define M4U_PORT_VENC_REC		MTK_M4U_ID(M4U_LARB3_ID, 1)
#define M4U_PORT_VENC_BSDMA		MTK_M4U_ID(M4U_LARB3_ID, 2)
#define M4U_PORT_VENC_SV_COMV		MTK_M4U_ID(M4U_LARB3_ID, 3)
#define M4U_PORT_VENC_RD_COMV		MTK_M4U_ID(M4U_LARB3_ID, 4)
#define M4U_PORT_JPGENC_RDMA		MTK_M4U_ID(M4U_LARB3_ID, 5)
#define M4U_PORT_JPGENC_BSDMA		MTK_M4U_ID(M4U_LARB3_ID, 6)
#define M4U_PORT_JPGDEC_WDMA		MTK_M4U_ID(M4U_LARB3_ID, 7)
#define M4U_PORT_JPGDEC_BSDMA		MTK_M4U_ID(M4U_LARB3_ID, 8)
#define M4U_PORT_VENC_CUR_LUMA		MTK_M4U_ID(M4U_LARB3_ID, 9)
#define M4U_PORT_VENC_CUR_CHROMA	MTK_M4U_ID(M4U_LARB3_ID, 10)
#define M4U_PORT_VENC_REF_LUMA		MTK_M4U_ID(M4U_LARB3_ID, 11)
#define M4U_PORT_VENC_REF_CHROMA	MTK_M4U_ID(M4U_LARB3_ID, 12)
#define M4U_PORT_VENC_NBM_RDMA		MTK_M4U_ID(M4U_LARB3_ID, 13)
#define M4U_PORT_VENC_NBM_WDMA		MTK_M4U_ID(M4U_LARB3_ID, 14)

/* larb4: motion judder compensation */
#define M4U_PORT_MJC_MV_RD		MTK_M4U_ID(M4U_LARB4_ID, 0)
#define M4U_PORT_MJC_MV_WR		MTK_M4U_ID(M4U_LARB4_ID, 1)
#define M4U_PORT_MJC_DMA_RD		MTK_M4U_ID(M4U_LARB4_ID, 2)
#define M4U_PORT_MJC_DMA_WR		MTK_M4U_ID(M4U_LARB4_ID, 3)

/* larb5: secondary display and MDP */
#define M4U_PORT_DISP_OVL1		MTK_M4U_ID(M4U_LARB5_ID, 0)
#define M4U_PORT_DISP_2L_OVL1		MTK_M4U_ID(M4U_LARB5_ID, 1)
#define M4U_PORT_DISP_RDMA1		MTK_M4U_ID(M4U_LARB5_ID, 2)
#define M4U_PORT_DISP_WDMA1		MTK_M4U_ID(M4U_LARB5_ID, 3)
#define M4U_PORT_DISP_OD_R		MTK_M4U_ID(M4U_LARB5_ID, 4)
#define M4U_PORT_DISP_OD_W		MTK_M4U_ID(M4U_LARB5_ID, 5)
#define M4U_PORT_DISP_2L_OVL0_LARB5	MTK_M4U_ID(M4U_LARB5_ID, 6)
#define M4U_PORT_MDP_RDMA1		MTK_M4U_ID(M4U_LARB5_ID, 7)
#define M4U_PORT_MDP_WROT1		MTK_M4U_ID(M4U_LARB5_ID, 8)
#define M4U_PORT_DISP_FAKE_LARB5	MTK_M4U_ID(M4U_LARB5_ID, 9)

/* larb6: image processor and DPE */
#define M4U_PORT_CAM_IMGI		MTK_M4U_ID(M4U_LARB6_ID, 0)
#define M4U_PORT_CAM_IMG2O		MTK_M4U_ID(M4U_LARB6_ID, 1)
#define M4U_PORT_CAM_IMG3O		MTK_M4U_ID(M4U_LARB6_ID, 2)
#define M4U_PORT_CAM_VIPI		MTK_M4U_ID(M4U_LARB6_ID, 3)
#define M4U_PORT_CAM_ICEI		MTK_M4U_ID(M4U_LARB6_ID, 4)
#define M4U_PORT_CAM_RP		MTK_M4U_ID(M4U_LARB6_ID, 5)
#define M4U_PORT_CAM_WR		MTK_M4U_ID(M4U_LARB6_ID, 6)
#define M4U_PORT_CAM_RB		MTK_M4U_ID(M4U_LARB6_ID, 7)
#define M4U_PORT_CAM_DPE_RDMA		MTK_M4U_ID(M4U_LARB6_ID, 8)
#define M4U_PORT_CAM_DPE_WDMA		MTK_M4U_ID(M4U_LARB6_ID, 9)

#endif
